### ISSUE TITLE
Hello ask a question

### ISSUE THREAD

**Issue by zhangzhongxin1994** [Nicholasli1995/EvoSkeleton#10]
could you please let me know whether the code for Heatmap Regression Model(Stage 1) parts already exists with the provided code？

**Comment by ben-xD** [comment]
I am interested in the answer too, as I believe Nicholas had to modify the models:

> While the original model predicts heat-maps of size 96 by 72, we append a pixel shufﬂe super-resolution layer [56] to the end and regress heat-maps of size 384 by 288. The original model [60] uses hard arg-max to predict 2D coordinates, which results in rounding errors in our experiments. Instead, we use soft arg-max [40, 62] to obtain 2D coordinates.

Additional question: Did you retrain HRNet for EvoSkeleton from scratch, or used the pretrained (on COCO or MPII?) `pose_hrnet_w32_384x288.pth` provided?

**Comment by Nicholasli1995** [comment]
Hi, the code for heatmap regression model training is adapted from https://github.com/leoxiaobin/deep-high-resolution-net.pytorch and is not included in this repo. The modified HRNet is pre-trained on COCO and fine-tuned on H36M. Pixelshuffle was added to up-sampling the predicted heatmap. I did not clean the stage 1 code as the focus of this repo is on 2D-to-3D lifting, but I can upload this part if many people think it's useful.

**Comment by zhangzhongxin1994** [comment]
Thank you for your quick reply,Thank you for your quick reply, I have understood your part of the work.Hope to see this part of the code in the future, thanks again!

**Comment by ben-xD** [comment]
> but I can upload this part if many people think it's useful.

I think it would be useful, as I am struggling with that at the moment. :)

**Comment by ben-xD** [comment]
How did the HRNet get fine-tuned on the H36M dataset? Did it involve preprocessing H36M?

**Comment by Nicholasli1995** [comment]
> How did the HRNet get fine-tuned on the H36M dataset? Did it involve preprocessing H36M?

Yes. The subjects were cropped from the video. The ground-truth key-points used for training were obtained by projecting 3D skeletons.

**Comment by Nicholasli1995** [comment]
Issues will be closed if there is no new discussion for more than one month. Re-open if needed.
