### ISSUE TITLE
Question about U3DPW and H36M

### ISSUE THREAD

**Issue by HyoKong** [Nicholasli1995/EvoSkeleton#11]
Hi, thank you very much for your excellent job!

Could you please explain how to use U3DPW as an augmented dataset for H36M? The keypoints on the H36M dataset and the U3DPW dataset are different. The visualization results of the 3d skeleton on two datasets are not totally the same.

Thank you very much for your help!

**Comment by Nicholasli1995** [comment]
> Hi, thank you very much for your excellent job!
> 
> Could you please explain how to use U3DPW as an augmented dataset for H36M? The keypoints on the H36M dataset and the U3DPW dataset are different. The visualization results of the 3d skeleton on two datasets are not totally the same.
> 
> Thank you very much for your help!

Hi, the U3DPW dataset was only used for validation and not used during training. We did not use U3DPW as augmented data. In addition, we only do data augmentation for 2D-to-3D networks. We did not do data augmentation when training the high-resolution heatmap regression model. 

I think it is possible to use U3DPW as augmented data for 2D pose estimation. However, if a few key-points does not match, the user need to manually correct them. The annotation style is quite similar to COCO or MPII.

**Comment by HyoKong** [comment]
Thank you so much for your reply! Is it possible to refine the annotation style from coco style to H36M style? I am glad to have a try if the aforementioned refinement is feasible.

**Comment by Nicholasli1995** [comment]
> Thank you so much for your reply! Is it possible to refine the annotation style of your proposed tools from the coco style to the H36M style? I am glad to have a try if the aforementioned refinement is feasible.

I'll mark this issue as a feature to add. I will discuss with other contributors @kp-kepra about adding H36M style annotation.

**Comment by HyoKong** [comment]
Thank you very much for your help! I'll close the issue.

**Comment by Nicholasli1995** [comment]
> Thank you very much for your help! I'll close the issue.

H36M style 2D annotation for U3DPW is now available.
