### ISSUE TITLE
Do you plan to publish part of the HRnet code?

### ISSUE THREAD

**Issue by fhbcff** [Nicholasli1995/EvoSkeleton#13]
Do you plan to publish part of the HRnet code?

**Comment by Nicholasli1995** [comment]
> Do you plan to publish part of the HRnet code?

The HR-Net training code will be added in a future update. However, the Human 3.6M videos will not be uploaded.

**Comment by Nicholasli1995** [comment]
> Do you plan to publish part of the HRnet code?

Hi, now the 2D pose estimation model is uploaded and the usage is available at https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/2DHPE.md.

**Comment by Nicholasli1995** [comment]
Re-open this issue if you need.
