### ISSUE TITLE
Missing "data" & "resource" folder?

### ISSUE THREAD

**Issue by emilyjiayaoli** [Nicholasli1995/EvoSkeleton#15]
I do not see any folder named "data" or "resources" inside the EvoSkeleton folder for the separately downloaded constraints and Human3.6 folders to be in mentioned in https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/HHR.md

**Comment by Nicholasli1995** [comment]
Hi, I have added the two folders. Previously I assume the user will create these two folders.

**Comment by Nicholasli1995** [comment]
Issues will be closed if there is no new discussion for more than one month. Re-open if needed.
