### ISSUE TITLE
TODO: Model Zoo for pre-trained models under different settings

### ISSUE THREAD

**Issue by John6333** [Nicholasli1995/EvoSkeleton#16]
It seems that the pre-trained model in examples.zip is weakly-supervised trained because it yields mpjpe of 50mm on GT 2D pose.
Where can I find the fully-supervised trained model, to reproduce the results 34.5 in Tab.3 in protocol P1*?

Thanks in advance.

**Comment by Nicholasli1995** [comment]
Will upload in a future update soon and notify you.

**Comment by nikky4D** [comment]
Hi, can you tell me if the model been updated to the fully-supervised version?

**Comment by Nicholasli1995** [comment]
Sorry that the authors are working on some new projects recently so they do not have plenty of time to maintain this repo. The next release should be expected in March, 2021 and the complete model Zoo will be available.

**Comment by nikky4D** [comment]
Thank you for the information. I look forward to the next release

**Comment by Nicholasli1995** [comment]
Sorry for the delay. The next release is planned within the next 2 weeks.

**Comment by Nicholasli1995** [comment]
> Hi, can you tell me if the model been updated to the fully-supervised version?



> It seems that the pre-trained model in examples.zip is weakly-supervised trained because it yields mpjpe of 50mm on GT 2D pose.
> Where can I find the fully-supervised trained model, to reproduce the results 34.5 in Tab.3 in protocol P1*?
> 
> Thanks in advance.

Hi, the new release updated pre-trained models. Protocol 1 and 2 are supported since they are more important. Please re-open this issue if there's any problem.
