### ISSUE TITLE
the input channel order to_spherical calculation

### ISSUE THREAD

**Issue by we1314love** [Nicholasli1995/EvoSkeleton#17]
hello, thanks for your outstanding work. I am learning the evolution part and had some questions about the to_spherical calculation.

in EvoSkeleton/libs/skeleton/anglelimits.py line179-192 is the function of to_spherical(xyz), and I have one questions:

1. according to the code, before calling  to_spherical(), the skeleton has been re_order to xzy, while the formula of to_spherical use the xyz order, so if the skeleton in xzy order input to to_spherical, can we still get the right result?

**Comment by Nicholasli1995** [comment]
Hi, I remembered that the original PosePrior used inputs that are in xzy order, so I did that before computing local orientation. You can refer to the matlab implementation of the original paper for details and ask further questions here.

**Comment by Nicholasli1995** [comment]
Closing inactive issues that already have answers. Re-open if needed.
