### ISSUE TITLE
2D Pose Estimation

### ISSUE THREAD

**Issue by leilaUEA** [Nicholasli1995/EvoSkeleton#18]
Hi, Is there a possibility to do 2D pose estimation of an arbitrary image with the current code that is uploaded? the inference code is uploading skeleton from a fixed, predefined dictionary of annotation....
Thanks very much in advance
Best regards,
Leila

**Comment by Nicholasli1995** [comment]
Hi, I will upload the pre-trained 2D pose estimator used in the paper tommorrow. However, this pre-trained model is only trained on H36M and may not be perfect for in-the-wild images. To get good performance on outdoor images, you can try:
1. Use other models trained on in-the-wild images.
2. Fine-tune my model with annotated outdoor images (like the provided U3DPW dataset).

**Comment by leilaUEA** [comment]
Thanks very much for your response and for uploading the 2D pose estimator, I appreciate it! 

I also tried running the annotator, annotate2D file, couldn't annotate as it didn't show red dots, I was wondering if it is because I am running under windows, or maybe the python environment is not completely matching in terms of packages or their versions..., it is showing the picture and environment but when I click nothing happens.

**Comment by leilaUEA** [comment]
regarding using other models, is there any other 2D pose estimation frameworks have the same 2d skeleton format? for example openpose body_25 and COCO models doesn't have the extra thorax and spine I think, and your 2D model is more accurate having two extra keypoint. Is there any other package that produces this kind of skeleton? does this model of skeleton have any name I can look for?

Thank you very much, appreciate your help

**Comment by Nicholasli1995** [comment]
> Hi, Is there a possibility to do 2D pose estimation of an arbitrary image with the current code that is uploaded? the inference code is uploading skeleton from a fixed, predefined dictionary of annotation....
> Thanks very much in advance
> Best regards,
> Leila

Hi, now the 2D pose estimation model is uploaded and the usage is available at https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/2DHPE.md.

**Comment by Nicholasli1995** [comment]
> Thanks very much for your response and for uploading the 2D pose estimator, I appreciate it!
> 
> I also tried running the annotator, annotate2D file, couldn't annotate as it didn't show red dots, I was wondering if it is because I am running under windows, or maybe the python environment is not completely matching in terms of packages or their versions..., it is showing the picture and environment but when I click nothing happens.

Is there any error message?

**Comment by Nicholasli1995** [comment]
> regarding using other models, is there any other 2D pose estimation frameworks have the same 2d skeleton format? for example openpose body_25 and COCO models doesn't have the extra thorax and spine I think, and your 2D model is more accurate having two extra keypoint. Is there any other package that produces this kind of skeleton? does this model of skeleton have any name I can look for?
> 
> Thank you very much, appreciate your help

I don't know other pre-trained model that can do H36M style 2D pose estimation for in-the-wild images. You may try my uploaded model first. If it does not work, one can try training a different 2D pose estimation model or 2D-to-3D lifting model.

**Comment by Nicholasli1995** [comment]
> @Nicholasli1995 Hi thank you for uploading your model. I was wondering where are images with the skeleton going? I can not find any after I run your pre-trained model.

Hi, I did not save them automatically since these images are just examples. You can save them yourself by running plt.savefig.

**Comment by Nicholasli1995** [comment]
Closing inactive issues that already have answers. Re-open if needed.
