### ISSUE TITLE
how to inference with wild image

### ISSUE THREAD

**Issue by hcyz33** [Nicholasli1995/EvoSkeleton#19]
hello, I want to use this model to predict some my wild picture . what should I do. How to get these 2d info of my picture.

**Comment by hcyz33** [comment]
hello, I have seen the code imgto2d .Could you share the pretrained model of it.

**Comment by Nicholasli1995** [comment]
> hello, I have seen the code imgto2d .Could you share the pretrained model of it.

Hi, now the 2D pose estimation model is uploaded and the usage is available at https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/2DHPE.md.

**Comment by Nicholasli1995** [comment]
Re-open if you have further questions.
