### ISSUE TITLE
I can't find the model

### ISSUE THREAD

**Issue by hcyz33** [Nicholasli1995/EvoSkeleton#2]
Hello, after reading your code, I found that the model file which should under the libs is missing.

**Comment by Nicholasli1995** [comment]
> Hello, after reading your code, I found that the model file which should under the libs is missing.

Sorry that was a bug in .gitignore file. I have fixed it and the missing file is now uploaded.

**Comment by hcyz33** [comment]
> Hello, after reading your code, I found that the model file which should under the libs is missing.
> 
> Sorry that was a bug in .gitignore file. I have fixed it and the missing file is now uploaded.

Thank you!
