### ISSUE TITLE
run question

### ISSUE THREAD

**Issue by zxp6329** [Nicholasli1995/EvoSkeleton#20]
hello,I want to ask Where can I see the data I evolved, and what exactly does the evolved_path  refer to?       (python 2Dto3Dnet.py -train True -num_stages 2 -ws True -ws_name "S1" -twoD_source "HRN/synthetic"  -evolved_path "YourDataPath")
 Can you give me an example? Thank you very much!

**Comment by zxp6329** [comment]
I see.thank you!

**Comment by Nicholasli1995** [comment]
Closing inactive issues that already have answers. Re-open if needed.
