### ISSUE TITLE
eval on 3DHP

### ISSUE THREAD

**Issue by gravitychen** [Nicholasli1995/EvoSkeleton#22]
nice code, nice paper, nice job!
my question is :
Can you provide the code for evaluating the 3DHP datasets,(e.x. pck3d & AUC calculation) or share other repositories that have the eval. code

**Comment by Nicholasli1995** [comment]
> nice code, nice paper, nice job!
> my question is :
> Can you provide the code for evaluating the 3DHP datasets,(e.x. pck3d & AUC calculation) or share other repositories that have the eval. code

Hi, the evaluation code (written in MATLAB) can be downloaded from the official website "http://gvv.mpi-inf.mpg.de/3dhp-dataset/". You can also take a look at OriNet (https://github.com/chenxuluo/OriNet-demo) about how to use the evaluation code.

**Comment by gravitychen** [comment]
Thank you very much!

**Comment by gravitychen** [comment]
dear author,

        I wonder whether the MPI pre-train model was released or not? I follow [the link](https://drive.google.com/file/d/158oCTK-9Y8Bl9qxidoHcXfqfeeA7qT93/view) to download the pre-train model, but when I inference it, It seems to have a different result to the paper described, which is 500+ MPJPE

thank a lot(BTW can I add your WeChat to talk more details?)

**Comment by Nicholasli1995** [comment]
> dear author,
> I wonder whether the MPI pre-train model was released or not? I follow [the link](https://drive.google.com/file/d/158oCTK-9Y8Bl9qxidoHcXfqfeeA7qT93/view) to download the pre-train model, but when I inference it, It seems to have a different result to the paper described, which is 500+ MPJPE
> 
> thank a lot(BTW can I add your WeChat to talk more details?)

The released pre-trained model should reproduce the results for 3DHP dataset. 500+ MPJPE is unreasonable and there may be something wrong. Please send me an email and we can discuss in more details.

**Comment by gravitychen** [comment]
Thank you so much
