### ISSUE TITLE
about training data 

### ISSUE THREAD

**Issue by gravitychen** [Nicholasli1995/EvoSkeleton#23]
The paper said there are 8M 2d-3d pairs, but the total number of the released h36m training data pairs is about 390k before augmentation, is that the correct number?

So if I guess right, that means you only take one h36m camera for each action instead of using 4 cameras for each action. 

I don't know whether my guess is correct, so  I post this issue to make sure. 

Thank you in advance.

**Comment by Nicholasli1995** [comment]
> The paper said there are 8M 2d-3d pairs, but the total number of the released h36m training data pairs is about 390k before augmentation, is that the correct number?
> 
> So if I guess right, that means you only take one h36m camera for each action instead of using 4 cameras for each action.
> 
> I don't know whether my guess is correct, so I post this issue to make sure.
> 
> Thank you in advance.

Hi, each view produces a unique 2D-3D pair. Thus 4 views give 390k * 4 = 1.6M 2D-3D pairs. By choosing larger number of generations (this will lead to longer data synthesis time), larger number of viewpoints, more diverse configuration of bone lengths (e.g., for children) one can generate more 2D-3D pairs as he wants. One can control the size/variation of the training data depending on his need.

**Comment by gravitychen** [comment]
OK, Thank you for your answer!
