### ISSUE TITLE
Cannot use the annotation tool

### ISSUE THREAD

**Issue by KingODB** [Nicholasli1995/EvoSkeleton#24]
After open the 2D annotation tool, the picture will show but cannot be labelled. Only the shortcut command for quit will work, the others won't. The 3D annotation cannot initiate for the missing file "jointAngleModel_v2.npy". Will you please re-upload the full package of this annotation tool, or did I ignore something?

**Comment by Nicholasli1995** [comment]
> After open the 2D annotation tool, the picture will show but cannot be labelled. Only the shortcut command for quit will work, the others won't. The 3D annotation cannot initiate for the missing file "jointAngleModel_v2.npy". Will you please re-upload the full package of this annotation tool, or did I ignore something?

Hi, can you share some error message is any for the 2D pose estimation?
For the missing file, it can be downloaded here:https://drive.google.com/drive/folders/1MUcR9oBNUpTAJ7YUWdyVLKCQW874FszI.
You can refer to https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/HHR.md to prepare the files.

**Comment by Nicholasli1995** [comment]
Please re-open this issue if there's further question.

**Comment by bijaydas-gyrus** [comment]
i am having the same issue, and there is no error message. it does nothing when i click on it

**Comment by Nicholasli1995** [comment]
> i am having the same issue, and there is no error message. it does nothing when i click on it

Can you share more information? What is your operating system, Python version and Matplotlib version?
