### ISSUE TITLE
AttributeError: module 'libs.dataset.h36m' has no attribute 'data_utils'

### ISSUE THREAD

**Issue by justintiger** [Nicholasli1995/EvoSkeleton#28]
Hi

Thx for this model. but i always get this error. Do you know whats the problem?

**Comment by Nicholasli1995** [comment]
It looks like a path problem. Can you show your running command, directory and full error message?

**Comment by justintiger** [comment]
> It looks like a path problem. Can you show your running command, directory and full error message?
> 
> > Hi
> > Thx for this model. but i always get this error. Do you know whats the problem?

(base) ihomelab@ihomelab-GPU-01:/mnt/sdb1/pose_estimation/3D_pose_estimation/EvoSkeleton/examples$ conda activate evoskeleton
(evoskeleton) ihomelab@ihomelab-GPU-01:/mnt/sdb1/pose_estimation/3D_pose_estimation/EvoSkeleton/examples$ python inference.py
Traceback (most recent call last):
  File "inference.py", line 9, in <module>
    from libs.dataset.h36m.data_utils import unNormalizeData
  File "../libs/dataset/h36m/data_utils.py", line 15, in <module>
    import libs.utils.utils as utils
  File "../libs/utils/utils.py", line 4, in <module>
    import libs.dataset.h36m.data_utils as data_utils
AttributeError: module 'libs.dataset.h36m' has no attribute 'data_utils'

**Comment by justintiger** [comment]
> It looks like a path problem. Can you show your running command, directory and full error message?
> 
> > Hi
> > Thx for this model. but i always get this error. Do you know whats the problem?

I have another question. Can this model give the 3D keypoints by using only images without 2D keypoints for the samples images?

**Comment by Nicholasli1995** [comment]
> > It looks like a path problem. Can you show your running command, directory and full error message?
> > > Hi
> > > Thx for this model. but i always get this error. Do you know whats the problem?
> 
> I have another question. Can this model give the 3D keypoints by using only images without 2D keypoints for the samples images?

Hi the problem is caused by a cyclic import bug introduced by a recent update. I have fixed it and you can pull the code and try again.

The lifting model need to has 2D keypoints as input. Images alone are not enough. However, you may use any available open-source 2D pose detector (openpose, SH, CPN and others... ) to get 2D keypoints. We have also released a 2D pose detector trained on H36M (see https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/2DHPE.md).

**Comment by Nicholasli1995** [comment]
Closing inactive issues. Re-open if you need further assistance.
