### ISSUE TITLE
How to make 2d pose estimation output .npy?

### ISSUE THREAD

**Issue by limeverry** [Nicholasli1995/EvoSkeleton#29]
Hello.
I want to run in the wild data using inference. but I don't know how to make 2d pose estimation output (.npy file).
According to what I understand, For making npy file, I should use h36m2Dpose.py or annotate_2D.p, right?

Can you explain how?

thank you.

**Comment by Nicholasli1995** [comment]
> Hello.
> I want to run in the wild data using inference. but I don't know how to make 2d pose estimation output (.npy file).
> According to what I understand, For making npy file, I should use h36m2Dpose.py or annotate_2D.p, right?
> 
> Can you explain how?
> 
> thank you.

Hi,
1.  If you want to use h36m2Dpose.py, you can refer to https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/2DHPE.md. The 2D pose outputs are visualized in that example.  You can save the 2D pose predictions with np.save().
2. If you want to use annotate_2D.py, you can refer to https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/ANNOTATOR.md. Pressing Z will save your annotated 2D key-points.

**Comment by limeverry** [comment]
> > Hello.
> > I want to run in the wild data using inference. but I don't know how to make 2d pose estimation output (.npy file).
> > According to what I understand, For making npy file, I should use h36m2Dpose.py or annotate_2D.p, right?
> > Can you explain how?
> > thank you.
> 
> Hi,
> 
> 1. If you want to use h36m2Dpose.py, you can refer to https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/2DHPE.md. The 2D pose outputs are visualized in that example.  You can save the 2D pose predictions with np.save().
> 2. If you want to use annotate_2D.py, you can refer to https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/ANNOTATOR.md. Pressing Z will save your annotated 2D key-points.

**Comment by limeverry** [comment]
Thank you for your help!

In my case, I want to use h36m2dpose.py . I think It is necessary to add 'np.save('filename.npy', pred)' on 120 line in h36m2Dpose.py. right?

In this case I have one concern. if I make .npy file as above, Does this result match the format of 3d pose estimation? In the case of 3d PE, I know that it has the same key as 'p2d'.

**Comment by Nicholasli1995** [comment]
Closing inactive issues. Re-open if you have further questions.
