### ISSUE TITLE
about jointAngle file

### ISSUE THREAD

**Issue by QuYJLeo** [Nicholasli1995/EvoSkeleton#3]
not upload jointAngleModel_v2 file

**Comment by Nicholasli1995** [comment]
> not upload jointAngleModel_v2 file

Hi, as mentioned in https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/HHR.md, the file can be downloaded at https://drive.google.com/drive/folders/1MUcR9oBNUpTAJ7YUWdyVLKCQW874FszI

**Comment by Nicholasli1995** [comment]
The file is already mentioned in the documentation. Re-open this issue if you need.
