### ISSUE TITLE
Test with a single image

### ISSUE THREAD

**Issue by alessiogatto** [Nicholasli1995/EvoSkeleton#30]
Hi, is it possible to perform inference from a single image chosen by me? I've noticed that, inside the examples folder, there is a file called "inference.py" but it uses the file "example_annot.npy" that contains the pre-calculated 2D key-points of the test images you say to download. Will a version of the inference code be released that will allow a single image (thus different from the ones you propose) to be used to test the network?

Thanks

**Comment by Nicholasli1995** [comment]
Hi, you can detect 2D pose with h36m2Dpose.py and then run 2D-to-3D lifting. See https://github.com/Nicholasli1995/EvoSkeleton/issues/29 for example.

> Hi, is it possible to perform inference from a single image chosen by me? I've noticed that, inside the examples folder, there is a file called "inference.py" but it uses the file "example_annot.npy" that contains the pre-calculated 2D key-points of the test images you say to download. Will a version of the inference code be released that will allow a single image (thus different from the ones you propose) to be used to test the network?
> 
> Thanks
