### ISSUE TITLE
About the coordinate system

### ISSUE THREAD

**Issue by NoLookDefense** [Nicholasli1995/EvoSkeleton#32]
Hi. I want to consult something about the coordinate system.
I saw that before evolution, there is a function called to_local(), which "represents the bone vectors in the local coordinate systems"
https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L285
I feel confused about this part. Will the coordinate be converted from camera coordinate to local coordinate? And what's definition of local coordinate and what's the meaning of the conversion?
BTW, it will be my honour if you are willing to provide me with some references. 
I am looking forward ton your reply.

**Comment by Nicholasli1995** [comment]
> Hi. I want to consult something about the coordinate system.
> I saw that before evolution, there is a function called to_local(), which "represents the bone vectors in the local coordinate systems"
> https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L285
> 
> 
> I feel confused about this part. Will the coordinate be converted from camera coordinate to local coordinate? And what's definition of local coordinate and what's the meaning of the conversion?
> BTW, it will be my honour if you are willing to provide me with some references.
> I am looking forward ton your reply.

Hi, each bone vector is represented in a local coodinate system. A local system is computed based on a 3D skeleton. The conversion is done with the inner product. The meaning of the conversion is: when the 3D pose is expressed in local systems, it is not affected by global rigid transformation. This makes it easier to represent a posture with joint angles. 

You can take a look at section 3.1 of the paper, as well as section 7 of the supplementary material (https://arxiv.org/pdf/2006.07778.pdf)

**Comment by NoLookDefense** [comment]
Thank you. I found that the angle of upper limb is limited by **angle_spread**
https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L20
, and the angle of lower limb is constrained by **sepPlane**
https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L22

But I feel confused about the **sepPlane**. As shown in the figure, it contains a list of a length 11. Some of them are empty and some of them contain a numpy array in the shape of (121, 61, 4) . In each numpy array, it has some values between [-1, 1], or nan. 

I feel extremely confused about this part. The size (121, 61) may mean the quantised result of spherical coordinates, but what about the third dimension 4? Also, what's the physical meaning of the values in each numpy array (like the nan)? 

I am looking forward to your reply. 

<img width="1264" alt="Screenshot 2021-05-30 at 15 05 11" src="https://user-images.githubusercontent.com/81567453/120095408-71797480-c158-11eb-94ab-748ff80601d6.png">

**Comment by Nicholasli1995** [comment]
> Thank you. I found that the angle of upper limb is limited by **angle_spread**
> https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L20
> 
> 
> , and the angle of lower limb is constrained by **sepPlane**
> https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L22
> 
> But I feel confused about the **sepPlane**. As shown in the figure, it contains a list of a length 11. Some of them are empty and some of them contain a numpy array in the shape of (121, 61, 4) . In each numpy array, it has some values between [-1, 1], or nan.
> 
> I feel extremely confused about this part. The size (121, 61) may mean the quantised result of spherical coordinates, but what about the third dimension 4? Also, what's the physical meaning of the values in each numpy array (like the nan)?
> 
> I am looking forward to your reply.
> 
> <img alt="Screenshot 2021-05-30 at 15 05 11" width="1264" src="https://user-images.githubusercontent.com/81567453/120095408-71797480-c158-11eb-94ab-748ff80601d6.png">

That is the vector used to define the separate plane. Conditioned on the parent bone orientation, this vector defines which half-sphere is valid. After projecting the bone vector to the separate plane, there is a bounding box as the valid region. The usage is shown here:
https://github.com/Nicholasli1995/EvoSkeleton/blob/f31e7c2e453cfb01cbb343c71f3d94dcf98efc4f/libs/skeleton/anglelimits.py#L105

See Figure 3 and Sec 3.2 of the reference: https://openaccess.thecvf.com/content_cvpr_2015/papers/Akhter_Pose-Conditioned_Joint_Angle_2015_CVPR_paper.pdf for more details.

**Comment by Nicholasli1995** [comment]
For future Q&A, please use the discussion function here: https://github.com/Nicholasli1995/EvoSkeleton/discussions.
Issues are only used for bug reporting and enhancement.
