### ISSUE TITLE
Question about the initial population

### ISSUE THREAD

**Issue by CheungBH** [Nicholasli1995/EvoSkeleton#36]
Hello. I want to ask some questions about initial 3d body-parts
I saw that the original 3d poses are loaded from the file "threeDPose_train.npy", and each sample has 96 dimensions.

<img width="261" alt="Screenshot 2021-06-07 at 09 19 54" src="https://user-images.githubusercontent.com/39186017/120947201-887c2000-c771-11eb-925b-2058dfe7141a.png">

I wonder what's the exact physical meaning of these values? Are they the absolute distance (use mm as the unit) in the local coordinate, where the center is the pelvis?

**Comment by Nicholasli1995** [comment]
> Hello. I want to ask some questions about initial 3d body-parts
> I saw that the original 3d poses are loaded from the file "threeDPose_train.npy", and each sample has 96 dimensions.
> 
> <img alt="Screenshot 2021-06-07 at 09 19 54" width="261" src="https://user-images.githubusercontent.com/39186017/120947201-887c2000-c771-11eb-925b-2058dfe7141a.png">
> 
> I wonder what's the exact physical meaning of these values? Are they the absolute distance (use mm as the unit) in the local coordinate, where the center is the pelvis?

These values are joint coordinates in the world coordinate system (32 X 3). The unit is mm. 17 out of 32 joints are used.

**Comment by Nicholasli1995** [comment]
For Q&A, please go to https://github.com/Nicholasli1995/EvoSkeleton/discussions.
Issues are used for bug reporting and enhancement. This issue will be closed.
