### ISSUE TITLE
The best way to correct 3D pose for multi-person dataset

### ISSUE THREAD

**Issue by KamiCalcium** [Nicholasli1995/EvoSkeleton#38]
Hi,

Thanks for the great work.

I have a dataset contains multi person's 3D pose. Some of them are not correct so I wanted to use your tool to correct those pose.

I'm not sure the best way of using the tools. This is what I have in my mind:

1. Crop the single person image using the bounding box from a multi person image.
2. Since I already have the 2D pose annotations, I will skip the 2D annotation, but do the 3D parameter fitting.
3. Then I will do the 3D annotations to correct the pose.
4. Merge every single person's result to the multi-person image.

Something that's not clear in my mind:

In step 1, I have all the 2D and 3D annotations for multiple person. However, they are global. If I crop to a single person image, should I change the pose annotations to local? Also since I crop the image from the bounding box, the size of every image will be different. Will that be a problem? I'm not sure what is the best way of doing it. It seems a lot of works.

Thanks in advance for answering my questions!

**Comment by Nicholasli1995** [comment]
> Hi,
> 
> Thanks for the great work.
> 
> I have a dataset contains multi person's 3D pose. Some of them are not correct so I wanted to use your tool to correct those pose.
> 
> I'm not sure the best way of using the tools. This is what I have in my mind:
> 
> 1. Crop the single person image using the bounding box from a multi person image.
> 2. Since I already have the 2D pose annotations, I will skip the 2D annotation, but do the 3D parameter fitting.
> 3. Then I will do the 3D annotations to correct the pose.
> 4. Merge every single person's result to the multi-person image.
> 
> Something that's not clear in my mind:
> 
> In step 1, I have all the 2D and 3D annotations for multiple person. However, they are global. If I crop to a single person image, should I change the pose annotations to local? Also since I crop the image from the bounding box, the size of every image will be different. Will that be a problem? I'm not sure what is the best way of doing it. It seems a lot of works.
> 
> Thanks in advance for answering my questions!

Actually you do not need to crop and run the fitting again. You can just plot the whole image and load your incorrect 3D pose parameters for one instance. In this way one instance will be annotated at a time.

Even if you want to run the fitting tool again, you do not need to crop. Giving the global 2D annotation to the fitting tool is enough. The images are just used for visualization, in fact the fitting tool does not need image to do its job.

**Comment by Nicholasli1995** [comment]
> Hi,
> 
> Thanks for the great work.
> 
> I have a dataset contains multi person's 3D pose. Some of them are not correct so I wanted to use your tool to correct those pose.
> 
> I'm not sure the best way of using the tools. This is what I have in my mind:
> 
> 1. Crop the single person image using the bounding box from a multi person image.
> 2. Since I already have the 2D pose annotations, I will skip the 2D annotation, but do the 3D parameter fitting.
> 3. Then I will do the 3D annotations to correct the pose.
> 4. Merge every single person's result to the multi-person image.
> 
> Something that's not clear in my mind:
> 
> In step 1, I have all the 2D and 3D annotations for multiple person. However, they are global. If I crop to a single person image, should I change the pose annotations to local? Also since I crop the image from the bounding box, the size of every image will be different. Will that be a problem? I'm not sure what is the best way of doing it. It seems a lot of works.
> 
> Thanks in advance for answering my questions!

If you have further questions, go to https://github.com/Nicholasli1995/EvoSkeleton/discussions. The issues are used for bug report.

**Comment by KamiCalcium** [comment]
Hi,

Thanks for answering. I've opened a discussion thread for follow-up of this question. Please kindly check it when you have time. Thanks!
