### ISSUE TITLE
Result is a bit strange 

### ISSUE THREAD

**Issue by hcyz33** [Nicholasli1995/EvoSkeleton#4]
Follow your guide, I generated some new data and trained the model with the data.
here is the command: 
**evolve**  `python evolve.py -generate True -WS True -SS "S1"`
**train**     `python 2Dto3Dnet.py -train True -num_stages 3 -ws True -ws_name "S1" -twoD_source "synthetic" -evolved_path "/home/hcy/project/3d_human_pose/EvoSkeleton-master/data/human3.6M/evolved/S1/evolved_data/generation_13.npy"`
After data enhancement, two files were generated , generation_1.npy and  generation_13.npy. I trained with the latter one. The result is a bit strange. After 200 epochs, you test the model with the test data.The picture below shows the test results.
![result](https://user-images.githubusercontent.com/50618241/88900712-5dd45780-d282-11ea-9cac-070056614b89.PNG)
I didn't change any code of your project. But the result is better than 50.5 which you showed on your paper .
I am curious why this happens.

**Comment by Nicholasli1995** [comment]
Hi, the code was cleaned and refined after the submission. Some minor bugs were corrected so the results may be a bit different. It's natural if the result is slightly better.

**Comment by Nicholasli1995** [comment]
Re-open this issue if you have further questions.
