### ISSUE TITLE
About one of the pre-trained models

### ISSUE THREAD

**Issue by jacksoncsy** [Nicholasli1995/EvoSkeleton#42]
Hello,

Thank you for sharing this great work, very solid and helpful!

I would like to ask about the pre-trained model provided under 'Inference Example' in: https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/TRAINING.md. The G-drive link is: https://drive.google.com/file/d/158oCTK-9Y8Bl9qxidoHcXfqfeeA7qT93/view

May I know which data do you use to train this model, as well as the parameters? I find it works perfectly in your proposed U3DPW dataset, while an EvoSkeleton model that I trained using synthetic H3.6m can only work on some of the example. Therefore, I wonder if this is because of the training data.

Many thanks,
Shiyang

**Comment by Nicholasli1995** [comment]
> Hello,
> 
> Thank you for sharing this great work, very solid and helpful!
> 
> I would like to ask about the pre-trained model provided under 'Inference Example' in: https://github.com/Nicholasli1995/EvoSkeleton/blob/master/docs/TRAINING.md. The G-drive link is: https://drive.google.com/file/d/158oCTK-9Y8Bl9qxidoHcXfqfeeA7qT93/view
> 
> May I know which data do you use to train this model, as well as the parameters? I find it works perfectly in your proposed U3DPW dataset, while an EvoSkeleton model that I trained using synthetic H3.6m can only work on some of the example. Therefore, I wonder if this is because of the training data.
> 
> Many thanks,
> Shiyang

Hi, there are two things to emphasize:
1. You need to set -norm_single to True when training an in-the-wild model. This will reduce the dataset bias to subject locations.
2. You can try generating more data with longer iterations and more viewpoints (by modifying the camera extrinsics).

**Comment by jacksoncsy** [comment]
Thank you so much! 
So the pre-trained model is trained on wild data, not Human3.6m?

**Comment by Nicholasli1995** [comment]
> Thank you so much!
> So the pre-trained model is trained on wild data, not Human3.6m?

No. It was trained on the synthetic data based on H36M. For Q&A, please go to discussion. Issues are used for bug report.

**Comment by jacksoncsy** [comment]
Thank you for your reply! 
I am pretty sure that one of the pre-trained models is not trained on synthetic Human3.6m, maybe we are not talking about the same model. Anyways, I will close this issue, and raise the discussion in Q&A.
