### ISSUE TITLE
Regarding the 2D HPE model

### ISSUE THREAD

**Issue by jacksoncsy** [Nicholasli1995/EvoSkeleton#44]
Hello,

I am trying to use your pre-trained 2D pose model to estimate 17 joints. 
May I know which architecture do you use for it, Stacked Hourglass? Also, what data do you use to train the model, are they 2D joints from Human3.6m?

Thanks,
Shiyang

**Comment by Nicholasli1995** [comment]
The architecture is HRNet-w48. The training data is 2D joints from H36M.

> Hello,
> 
> I am trying to use your pre-trained 2D pose model to estimate 17 joints.
> May I know which architecture do you use for it, Stacked Hourglass? Also, what data do you use to train the model, are they 2D joints from Human3.6m?
> 
> Thanks,
> Shiyang

**Comment by jacksoncsy** [comment]
Got it, thank you!
