### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by zhangzhongxin1994** [Nicholasli1995/EvoSkeleton#5]
Hello, the following error occurred when I was running the training code. May I ask what the problem is and how to solve it?
![image](https://user-images.githubusercontent.com/69120784/89129939-ef1e2500-d533-11ea-9a48-948cb4b36a03.png)

**Comment by mphirke** [comment]
I received the same error when I tried this on Colab. 

Not sure if this is the correct solution but changing line 242 on datautils.py solved it for me.

Change line 242 in EvoSkeleton/libs/dataset/h36m/data_utils.py from 
```
    else:
        # raw training data from Human 3.6M (S15678) 
        train_dict_3d = np.load(dict_path).item()
        return train_dict_3d   #line 242
```


to
```
    else:
        # raw training data from Human 3.6M (S15678) 
        train_dict_3d = np.load(dict_path).item()
    return train_dict_3d
```

**Comment by Nicholasli1995** [comment]
> Hello, the following error occurred when I was running the training code. May I ask what the problem is and how to solve it?
> ![image](https://user-images.githubusercontent.com/69120784/89129939-ef1e2500-d533-11ea-9a48-948cb4b36a03.png)

Sorry that was a typo when cleaning the code. The fix suggested by @mphirke is correct.

**Comment by zhangzhongxin1994** [comment]
Thank you. The problem has been solved
