### ISSUE TITLE
ImportError: No module named libs.hhr.config

### ISSUE THREAD

**Issue by dhruv-shindhe** [Nicholasli1995/EvoSkeleton#57]
I'm getting this error when I run python ./examples/h36m2Dpose.py

**Comment by Nicholasli1995** [comment]
> I'm getting this error when I run python ./examples/h36m2Dpose.py

You are not in the expected directory.
First "cd ${EvoSkeleton}/examples" then "python h36m2Dpose.py"

**Comment by dhruv-shindhe** [comment]
I get this error now 
from yacs.config import CfgNode as CN
ModuleNotFoundError: No module named 'yacs'

**Comment by Nicholasli1995** [comment]
> I get this error now
> from yacs.config import CfgNode as CN
> ModuleNotFoundError: No module named 'yacs'

Install it by "pip install yacs" or "conda install yacs".
