### ISSUE TITLE
AttributeError: module 'libs.utils' has no attribute 'utils'

### ISSUE THREAD

**Issue by tdat1995** [Nicholasli1995/EvoSkeleton#60]
Im training the network with 2Dto3Dnet.py with the cmd:
python 2Dto3Dnet.py -train True -num_stages 2 -ws True -ws_name "S1" -twoD_source "HRN/synthetic" -evolved_path "YourDataPath"
How ever it show the error:
Traceback (most recent call last):
  File "2Dto3Dnet.py", line 16, in <module>
    import libs.utils.utils as utils
  File "../libs/utils/utils.py", line 4, in <module>
    import libs.dataset.h36m.data_utils as data_utils
  File "../libs/dataset/h36m/data_utils.py", line 15, in <module>
    import libs.utils.utils as utils
AttributeError: module 'libs.utils' has no attribute 'utils'
Anyone can help me
Many thanks

**Comment by tdat1995** [comment]
I'm already run all the anaconda files follow by the spec-list.txt
And check conda list in my env and see all of below already correct:
- Python 3.6
- Numpy 1.16
- PyTorch 1.0.1
- CUDA 9

**Comment by Nicholasli1995** [comment]
> Im training the network with 2Dto3Dnet.py with the cmd: python 2Dto3Dnet.py -train True -num_stages 2 -ws True -ws_name "S1" -twoD_source "HRN/synthetic" -evolved_path "YourDataPath" How ever it show the error: Traceback (most recent call last): File "2Dto3Dnet.py", line 16, in import libs.utils.utils as utils File "../libs/utils/utils.py", line 4, in import libs.dataset.h36m.data_utils as data_utils File "../libs/dataset/h36m/data_utils.py", line 15, in import libs.utils.utils as utils AttributeError: module 'libs.utils' has no attribute 'utils' Anyone can help me Many thanks

It seems you are using an old version of the repo. This import bug should already be fixed long ago. Try git pull to update your repo.
https://github.com/Nicholasli1995/EvoSkeleton/blob/b2b355f4c1fa842709f100d931189ce80008f6ef/libs/dataset/h36m/data_utils.py#L15

**Comment by tdat1995** [comment]
Thank you so much after i update it have new error
Traceback (most recent call last):
  File "2Dto3Dnet.py", line 68, in <module>
    main()
  File "2Dto3Dnet.py", line 38, in main
    data_utils.prepare_dataset(opt)
  File "../libs/dataset/h36m/data_utils.py", line 812, in prepare_dataset
    predict_14=False
  File "../libs/dataset/h36m/data_utils.py", line 366, in prepare_data_dict
    assert opt.twoD_source in ['synthetic', 'HRN'], 'Unknown 2D key-point type.'
AssertionError: Unknown 2D key-point type.
Do you know how to fix it?
Thanks

**Comment by Nicholasli1995** [comment]
> Thank you so much after i update it have new error Traceback (most recent call last): File "2Dto3Dnet.py", line 68, in main() File "2Dto3Dnet.py", line 38, in main data_utils.prepare_dataset(opt) File "../libs/dataset/h36m/data_utils.py", line 812, in prepare_dataset predict_14=False File "../libs/dataset/h36m/data_utils.py", line 366, in prepare_data_dict assert opt.twoD_source in ['synthetic', 'HRN'], 'Unknown 2D key-point type.' AssertionError: Unknown 2D key-point type. Do you know how to fix it? Thanks

Pass arguments as -twoD_source "HRN" or -twoD_source "synthetic" depending on your need. 
-twoD_source "HRN/synthetic" is not correct.

**Comment by tdat1995** [comment]
Thank you so much for your help. Now I already can train the model. 
Wish you have a nice days
