### ISSUE TITLE
2D to 3D with own data

### ISSUE THREAD

**Issue by dwygs** [Nicholasli1995/EvoSkeleton#62]
hi
I tried your 'inference.py' module with own 2d data, but the result has some problems：
![image](https://user-images.githubusercontent.com/92436095/137465240-5a15e4cb-23de-4442-81ab-c93538e73be4.png)
![image](https://user-images.githubusercontent.com/92436095/137465298-0367fe0e-0fbd-4a06-aba6-f6b28ca2e984.png)
The reason is that your output  need to use human3.6's 3d_mean and std to decode, but my data will produce errors if I use this decoding method, So I want to ask you how can I solve this kind of problem.
thank you very much！

**Comment by Nicholasli1995** [comment]
> hi I tried your 'inference.py' module with own 2d data, but the result has some problems： ![image](https://user-images.githubusercontent.com/92436095/137465240-5a15e4cb-23de-4442-81ab-c93538e73be4.png) ![image](https://user-images.githubusercontent.com/92436095/137465298-0367fe0e-0fbd-4a06-aba6-f6b28ca2e984.png) The reason is that your output need to use human3.6's 3d_mean and std to decode, but my data will produce errors if I use this decoding method, So I want to ask you how can I solve this kind of problem. thank you very much！

Can you elaborate why the decoding method causes problem for your data?

**Comment by dwygs** [comment]
Thank you for your reply，
The length of my bones is shorter than that of human 3.6, which is considered to be inclined to the depth direction, so I think the bone mean and variance calculated by human 3.6 are not applicable to my own data. Is this understanding correct?  I want to know whether it is the cause of the network or  the 'unNormalizeData' module .
Thanks for your code and answers ！

**Comment by Nicholasli1995** [comment]
> Thank you for your reply， The length of my bones is shorter than that of human 3.6, which is considered to be inclined to the depth direction, so I think the bone mean and variance calculated by human 3.6 are not applicable to my own data. Is this understanding correct? I want to know whether it is the cause of the network or the 'unNormalizeData' module . Thanks for your code and answers ！

Your annotation for the leg maybe too short and the network thinks it corresponds to a person in another viewpoint. unNormalizeData should be OK but the input annotation style can be modified a bit. You may try lift the hip key-points higher to see if it helps. Otherwise you may also modify the training bone length/pose according to your need and re-train a network.

**Comment by dwygs** [comment]
Thanks！
I tried to modify the bone length and it can indeed be made correct.

**Comment by sunmengnan** [comment]
> Thanks！ I tried to modify the bone length and it can indeed be made correct.

How did you find these length is shorter? as I see it, they are normal.

**Comment by dwygs** [comment]
> 
> How did you find these length is shorter? as I see it, they are normal.

You can see the picture I showed, the second one is rotated by an angle so that you can see the depth information, you can see that it is different from the pose in the image
