### ISSUE TITLE
Query on Keypoint order for Inference in the wild

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [Nicholasli1995/EvoSkeleton#7]
Hey, in the `inference.py` file, it reads the `example_annot.npy` for annotations. Can you please tell me which indices correspond to which keypoints? Thanks!

**Comment by Nicholasli1995** [comment]
> Hey, in the `inference.py` file, it reads the `example_annot.npy` for annotations. Can you please tell me which indices correspond to which keypoints? Thanks!

Hi, the order is the same as Human 3.6M annotation except that the nose is not used in this example. The order for the 2D keypoints is: 'Hip', 'RHip', 'RKnee', 'RFoot', 'LHip', 'LKnee', 'LFoot', 'Spine', 'Thorax', 'Neck/Nose', 'Head', 'LShoulder', 'LElbow', 'LWrist', 'RShoulder', 'RElbow', 'RWrist'.

I have updated the code and the key-point indices are shown during visualization.

**Comment by Ashwin-Ramesh2607** [comment]
Thanks!
