### ISSUE TITLE
Input of the plot_distribution in anglelimits.py

### ISSUE THREAD

**Issue by lfl960124** [Nicholasli1995/EvoSkeleton#70]
Hi, how can  I obtain the H_temp?

**Comment by Nicholasli1995** [comment]
> Hi, how can I obtain the H_temp?

Hi, you can use any function that can compute a histogram. Please direct questions to the Q&A section in discussions.

**Comment by lfl960124** [comment]
> 我有另外一个问题想请教一下，为什么用HUMAN3.6的原始数据集，用评估合理姿态函数后还有显示是FALSE呢？

**Comment by Nicholasli1995** [comment]
> > 我有另外一个问题想请教一下，为什么用HUMAN3.6的原始数据集，用评估合理姿态函数后还有显示是FALSE呢？

主要是因为评估合理姿态函数也是从一些采集的人体骨骼的统计数据得到的,那些数据和H36M里面采集的数据的关键点的语义不完全匹配.H36M的数据相对于合理函数采集的原始数据就像加了噪声的数据,所以会有一些误判.

**Comment by lfl960124** [comment]
您好，抱歉打扰啦，我今天跑了一下human3.6的关节范围，gamma设置0.5，与最后交叉变异后的数据范围图很接近，想请教一下，论文中的关节范围图中gamma设置为多少呀？
