### ISSUE TITLE
Obtain 3D skeleton with 2D key-points as inputs using SMPLify by own data

### ISSUE THREAD

**Issue by tdat1995** [Nicholasli1995/EvoSkeleton#77]
Thank you so much for providing the code also now I met the problem when I want to obtain a 3D skeleton with 2D keypoint.
The error is like this when I run the code
"python fit_3d.py -dataset_dir anno -model_dir smplify/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl"
Traceback (most recent call last):
  File "fit_3d.py", line 99, in <module>
    main(opt)
  File "fit_3d.py", line 62, in main
    do_degrees=do_degrees
  File "/home/panda/EvoSkeleton/libs/annotator/smplify/fit_3d.py", line 451, in run_single_fit
    viz=viz)
  File "/home/panda/EvoSkeleton/libs/annotator/smplify/fit_3d.py", line 120, in initialize_camera
    center = np.array([img.shape[1] / 2, img.shape[0] / 2])
AttributeError: 'NoneType' object has no attribute 'shape'

It shows that it can not use my 2D input keypoint. Many thanks

**Comment by 2samgu2** [comment]
img is None
Match the image path in annotation path

**Comment by Nicholasli1995** [comment]
> Thank you so much for providing the code also now I met the problem when I want to obtain a 3D skeleton with 2D keypoint. The error is like this when I run the code "python fit_3d.py -dataset_dir anno -model_dir smplify/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl" Traceback (most recent call last): File "fit_3d.py", line 99, in main(opt) File "fit_3d.py", line 62, in main do_degrees=do_degrees File "/home/panda/EvoSkeleton/libs/annotator/smplify/fit_3d.py", line 451, in run_single_fit viz=viz) File "/home/panda/EvoSkeleton/libs/annotator/smplify/fit_3d.py", line 120, in initialize_camera center = np.array([img.shape[1] / 2, img.shape[0] / 2]) AttributeError: 'NoneType' object has no attribute 'shape'
> 
> It shows that it can not use my 2D input keypoint. Many thanks

Hi, please check your paths to your input images.

**Comment by tdat1995** [comment]
Thank you so much guys
