### ISSUE TITLE
I wonder why your model is "cascaded"

### ISSUE THREAD

**Issue by uyoung-jeong** [Nicholasli1995/EvoSkeleton#9]
When I think about 'cascaded network', I come up with a network of modules connected in consecutive order, just like cascaded pyramid network(CPN).
In your implementation, every stage gets 2D skeleton inputs, and generates 3D skeleton estimations.
And the estimation loss is just the difference between the target and the sum of their estimations.
Therefore, I think that your 2D-to-3D estimation network is composed of multiple 2D-to-3D estimation models bagged together.
Of course, the gradient flows through every stage. 
But the latter stage does not get the output of the former stage, so they are not connected sequentially.

**Comment by Nicholasli1995** [comment]
Hi, this is a good question.  

Quote: "I come up with a network of modules connected in consecutive order, just like cascaded pyramid network(CPN)."
Actually by cascade we mean the first stage gives an initial guess and the later stages refine the prediction. Ours is more similar to reference [9] and [49] which were published **before** CPN. In fact, they were not even based on deep learning.

Quote: "I think that your 2D-to-3D estimation network is composed of multiple 2D-to-3D estimation models bagged together.......But the latter stage does not get the output of the former stage, so they are not connected sequentially."
The code has an deprecated option "refine_3d" which implements the "sequential" version. Enabling this will feed the current estimate to the later stages, which means the deep learners in different stages have different inputs (not bagging). However, as we explain at Section 2.1 in our supplementary material (included in the arxiv version), this option did not make much difference and was removed from the default setting.

Quote: "the gradient flows through every stage"
Actually each stage is trained separately as expained in Algorithm 3 in the supplementary material. The gradient does not flow through every stage. 

Quote: "every stage gets 2D skeleton inputs, and generates 3D skeleton estimations."
Each stage has different regression targets. The later stages regress residual.

**Comment by Nicholasli1995** [comment]
Re-open if you have further question.

**Comment by Garfield-kh** [comment]
May I ask a question about this cascaded strategy?
After reading the code, the method here is to train the 1st stage model to have an initial guess, then the following stage will try to predict the residue (error by ` dataset.stage_update` ) of previous stage prediction. However, I feel that using a model B to predict the error of model A could be very hard, how does it work here?
Thank you.

**Comment by Garfield-kh** [comment]
> > May I ask a question about this cascaded strategy?
> > After reading the code, the method here is to train the 1st stage model to have an initial guess, then the following stage will try to predict the residue (error by ` dataset.stage_update` ) of previous stage prediction. However, I feel that using a model B to predict the error of model A could be very hard, how does it work here?
> > Thank you.
> 
> Hi, the working principle of this cascade is similar to some previous works on boosted regression, which combines multiple linear regressors. In this work we use DNN instead of linear regressors.
> 
> We believe the 2D-to-3D lifting function is hard to approximate for a single DNN. We thus combine multiple deep learners to obtain a stronger model. Empirically the training and generalization error were both reduced.
> 
> Thinking in the view of model combination, the collection of multiple regression models usually give smaller generation error than a single model (As a reference, some theoretical proof can be found at chapter 14 of Bishop C M. Pattern recognition and machine learning[M]. springer, 2006).

Thank you for the answer. 
In fact I have tried use two model, one for initial guess, another for error regression. The end2end training does not help on the performance. 
However, train one and fix first, then train another one for the error regression really works here.

**Comment by ben-xD** [comment]
![your image](https://github.com/Nicholasli1995/EvoSkeleton/blob/master/imgs/architecture.jpg)

Is it true that all 3 'deep learners' in your cascade take a (1,2*k) input as shown in the image? If this is true, how does the 3D joints in the top image get converted into (1, 2*k) as input into the deep learner (bottom image)?
